# Generated by Django 2.0.6 on 2018-07-02 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodsite', '0002_apimodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
