# Generated by Django 2.0.6 on 2018-07-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsite', '0003_auto_20180702_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimodel',
            name='limit',
            field=models.IntegerField(default=500),
        ),
    ]
