# Generated by Django 2.0.6 on 2018-07-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsite', '0007_auto_20180702_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimodel',
            name='apikey',
            field=models.CharField(default=None, max_length=25, unique=True),
        ),
    ]
